version: "3"

services:
    php:
        build:
            context: ./docker/config/php
            args:
                uid: '${UID}'
        volumes:
            - ${PROJECT_VOLUME}:/application:cached
        user: '${UID}'
        networks:
            - test_network
    nginx:
        image: nginx:latest
        ports:
            - 8000:8000
        volumes:
            - ./docker/config/nginx/base.conf:/etc/nginx/nginx.conf
            - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ${PROJECT_VOLUME}:/application:cached
            - ./docker/server/nginx/:/var/log/nginx
        depends_on:
            - php
        networks:
            - test_network
networks:
    test_network:
        driver: bridge
